[phases.setup]
nixPkgs = ["nodejs_20", "python3", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma migrate deploy && node dist/index.js"
